### ISSUE TITLE
Missing file `data/clusters.tsv`

### ISSUE THREAD

**Issue by erip** [SapienzaNLP/reducing-wsd-bias-in-nmt#1]
Thanks for the code! I tried running the pretraining script from the README but was met with:

```python
Traceback (most recent call last):
  File "/home/erip/reducing-wsd-bias-in-nmt/src/main.py", line 9, in <module>
    from data.datamodule import WSDMTDataModule
  File "/home/erip/reducing-wsd-bias-in-nmt/src/data/datamodule.py", line 9, in <module>
    from data.encoder import SentenceBatchEncoder
  File "/home/erip/reducing-wsd-bias-in-nmt/src/data/encoder/__init__.py", line 9, in <module>
    from data.encoder.cluster import ClusteredSenseSentenceBatchEncoder
  File "/home/erip/reducing-wsd-bias-in-nmt/src/data/encoder/cluster.py", line 21, in <module>
    class ClusteredSenseSentenceBatchEncoder(SenseSentenceBatchEncoder):
  File "/home/erip/reducing-wsd-bias-in-nmt/src/data/encoder/cluster.py", line 22, in ClusteredSenseSentenceBatchEncoder
    _CLUSTERING = load_synset_clustering()
  File "/home/erip/reducing-wsd-bias-in-nmt/src/data/encoder/cluster.py", line 12, in load_synset_clustering
    for line in open('data/clusters.tsv'):
FileNotFoundError: [Errno 2] No such file or directory: 'data/clusters.tsv'
```

I looked through the README but it wasn't clear whether this should've been included, generated, or downloaded.

**Comment by Valahaar** [comment]
Hi, and thanks for taking an interest in our work!

It's my fault, I forgot to remove some code related to experiments which did not make it into the final paper. 
I have updated the repository, it should be working now. I haven't had the chance to test it though, so if you have any issues don't hesitate to point them out :)
